first_categories_header:
  type: string
  default: "First Categories Header"
first_categories:
  type: list
  list_type: category
  default: ""
  description: "Chose the categories to feature for the First Header"
